---
- name: Provision HCP cluster
  hosts: localhost
  

  tasks:
    - name: Create temporary directory with write access for playbook user
      file:
        path: /tmp/hcp_install
        state: directory
        mode: 0755  # Allows user to read, write, execute, and group/others can only read and execute

    - name: Download HCP archive to temporary directory
      uri:
        url: https://hcp-cli-download-multicluster-engine.apps.mgm2.tmetse.bos2.lab/linux/amd64/hcp.tar.gz
        dest: /tmp/hcp_install/hcp.tar.gz
        mode: 0644
        validate_certs: no 

    - name: Unpack HCP archive using unarchive module
      ansible.builtin.unarchive:
        src: /tmp/hcp_install/hcp.tar.gz
        dest: /tmp/hcp_install 
    
    - name: Make HCP binary executable
      file:
        path: /tmp/hcp_install/hcp
        mode: +x
        owner: 
        group: 
        

    - name: Export cluster variables
      set_fact:
        CLUSTER_NAME: "hcp{{ 100 | random }}"
        MEM: 16Gi
        CPU: 8
        WORKER_COUNT: 2
        ETCD_STORAGE: ocs-storagecluster-ceph-rbd
        OCP_RELEASE: 4.14.11-x86_64
        PULL_SECRET: "{{ lookup('env', 'PULL_SECRET')}}"
        INFRA_CLUSTER: "{{ lookup('env', 'INFRA_KUBECONFIG')}}"
        
    
    - name: Create KubeVirt cluster
      command: /tmp/hcp_install/hcp create cluster kubevirt \
               --name "{{ CLUSTER_NAME }}" \
               --node-pool-replicas=2 \
               --memory "{{MEM}}" \
               --cores "{{CPU}}" \
               --pull-secret "{{ PULL_SECRET}}" \
               --release-image=quay.io/openshift-release-dev/ocp-release:4.14.11-x86_64 \
               --etcd-storage-class= ocs-storagecluster-ceph-rbd
               --infra-namespace=example-workers \
               --infra-kubeconfig-file "{{ INFRA_CLUSTER }}"
      
 
